### ISSUE TITLE
Spamming errors at KSP Main Menu

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/ksp_toolbar#15]
This gets spammed every time the main menu gets loaded:

_[ERR 16:21:43.535] ToolbarControl: WARNING: RegisterMod, LoadedScene: MAINMENU, called too late for: PartCommander_NS, Part Commander, button may not be registered properly

[ERR 16:21:43.547] ToolbarControl: WARNING: RegisterMod, LoadedScene: MAINMENU, called too late for: RCSBuildAid_NS, RCS Build Aid, button may not be registered properly_

A few other mods also gets reported.
Full log here: [Full Log at Mediafire](http://www.mediafire.com/file/0r99nr2qfgdn8pw/KSP%25285%2529.log/file)

Also, is it really necessary to have a MAINMENU section in the Toolbar-Settings.dat file? It gets filled with non sense toolbar definitions even though no toolbar were explicitly created there:

_MAINMENU
	{
		toolbar_112650527
		{
			x = 1580
			y = -3
			width = 733
			height = 38
			autoHide = False
			drawBorder = False
			useKSPSkin = True
			buttonOrder = __TOOLBAR_INTERNAL.configureVisibleButtons,KerbalAlarmClock.btnToolbarIcon,ScienceChecklist.checklist_button,test.buttonDOSettings,ThrottleControlledAvionics.ThrottleControlledAvionicsButton,ToolbarController_NS.toolbarControllerButton,AmpYear.button1,WALKABOUT_NS.walkaboutButton,FinalFrontier.button,TACLifeSupport.button1,SCANsat.KSCMap,BetterTimeWarp_NS.betterTimeWarpButton,ContractsWindow.ContractWindowPlus,Kerbal_Construction_Time.MainButton
			visibleButtons = test.buttonDOSettings,BetterTimeWarp_NS.betterTimeWarpButton,FinalFrontier.button,HaystackReContinued_NS.haystackContinuedButton,Patchmanger_NS.patchManagerButton﻿,SCANsat.KSCMap,ferram4.FARDebugButtonBlizzy,Kerbal_Construction_Time.MainButton,ScienceChecklist.checklist_button,ScienceChecklist.status_button,TACLifeSupport.button1,ContractsWindow.ContractWindowPlus,KerbalAlarmClock.btnToolbarIcon,ThrottleControlledAvionics.ThrottleControlledAvionicsButton,ContractRewardModifier.CMToolbarID,WALKABOUT_NS.walkaboutButton,AmpYear.button1
		}
		toolbar_1383093420
		{
			x = 1678
			y = -3
			width = 571
			height = 38
			autoHide = False
			drawBorder = False
			useKSPSkin = True
			buttonOrder = __TOOLBAR_INTERNAL.configureVisibleButtons,BetterTimeWarp_NS.betterTimeWarpButton,KerbalAlarmClock.btnToolbarIcon,RCSBuildAid_NS.RCSBuildAidButton,FinalFrontier.button,ThrottleControlledAvionics.ThrottleControlledAvionicsButton,WASD_NS.wasdButton,ReCoupler.ReCoupler,AmpYear.button1,TACLifeSupport.button1,ScienceChecklist.checklist_button,ContractsWindow.ContractWindowPlus,Kerbal_Construction_Time.MainButton,WaypointManager.button
			visibleButtons = BetterTimeWarp_NS.betterTimeWarpButton,FinalFrontier.button,HaystackReContinued_NS.haystackContinuedButton,Kerbal_Construction_Time.MainButton,PartWizard_NS.partWizardButton,RCSBuildAid_NS.RCSBuildAidButton,sirkut.IRButton,StageRecovery_NS.stageControlButton,WASD_NS.wasdButton,WaypointManager.button,ScienceChecklist.checklist_button,ScienceChecklist.status_button,KerbalAlarmClock.btnToolbarIcon,TACLifeSupport.button1,ContractsWindow.ContractWindowPlus,ThrottleControlledAvionics.ThrottleControlledAvionicsButton,AmpYear.button1,ReCoupler.ReCoupler
		}
		toolbar_2110259249
		{
			x = 753
			y = -3
			width = 250
			height = 38
			autoHide = False
			drawBorder = False
			useKSPSkin = True
			buttonOrder = __TOOLBAR_INTERNAL.configureVisibleButtons,MechJeb2.Custom_Window_Editor,MechJeb2.Design_Info,MechJeb2.Delta-V_Stats
			visibleButtons = MechJeb2.Design_Info,MechJeb2.Delta-V_Stats,MechJeb2.Custom_Window_Editor,MechJeb2.MechJeb2MenuButton
		}
		toolbar_1582030038
		{
			x = 1106
			y = 1045
			width = 1142
			height = 38
			autoHide = False
			drawBorder = True
			useKSPSkin = True
			buttonOrder = __TOOLBAR_INTERNAL.configureVisibleButtons,SCANsat.UIMenu,KerbalAlarmClock.btnToolbarIcon,ScienceChecklist.checklist_button,FinalFrontier.button,PersistentRotation.button,TACLifeSupport.button1,AmpYear.button1,Trajectories.TrajectoriesGUI,WaypointManager.button,ThrottleControlledAvionics.ThrottleControlledAvionicsButton,TWR1_NS.flightPlanButton
			visibleButtons = FerramAerospaceResearch.FARFlightButtonBlizzy,FinalFrontier.button,ScienceChecklist.status_button,ScienceChecklist.checklist_button,SCANsat.UIMenu,TWR1_NS.flightPlanButton,WaypointManager.button,KerbalAlarmClock.btnToolbarIcon,TACLifeSupport.button1,HaystackReContinued_NS.haystackContinuedButton,ThrottleControlledAvionics.ThrottleControlledAvionicsButton,AmpYear.button1,Trajectories.TrajectoriesGUI
		}
		toolbar_49774081
		{
			x = 211
			y = -35
			width = 250
			height = 38
			autoHide = True
			drawBorder = True
			useKSPSkin = True
			buttonOrder = 
			visibleButtons = BetterTimeWarp_NS.betterTimeWarpButton
		}
		toolbar_1849895569
		{
			x = 661
			y = 1077
			width = 435
			height = 38
			autoHide = True
			drawBorder = True
			useKSPSkin = True
			buttonOrder = __TOOLBAR_INTERNAL.configureVisibleButtons,CriticalTemperatureGauge.CriticalTemperatureGaugeSettings,HotSpot.config,KerbalFlightData.KerbalFlightData,NavHud_NS.navhudButton,PlanetShine.Gui,test.buttonDOSettings,SmokeScreen.main,PersistentRotation.button,KerbalFlightIndicators.KerbalFlightIndicators,MechJeb2.Aircraft_Data_Panel
			visibleButtons = HotSpot.config,CriticalTemperatureGauge.CriticalTemperatureGaugeSettings,KerbalFlightIndicators.KerbalFlightIndicators,KerbalFlightData.KerbalFlightData,NavHud_NS.navhudButton,PlanetShine.Gui,SmokeScreen.main,test.buttonDOSettings,MechJeb2.Custom_Info_Window,MechJeb2.Aircraft_Data_Panel,PersistentRotation.button,SurfaceExperimentPackage.SEPController
		}
		toolbar_1223376630
		{
			x = 204
			y = 1077
			width = 250
			height = 38
			autoHide = True
			drawBorder = True
			useKSPSkin = True
			buttonOrder = 
			visibleButtons = ABFW_NS.abfwButton,EvaEnhancements_NS.evaEnhancementsButton
		}
		toolbar_1238406290
		{
			x = 1742
			y = 1045
			width = 250
			height = 38
			autoHide = False
			drawBorder = True
			useKSPSkin = True
			buttonOrder = __TOOLBAR_INTERNAL.configureVisibleButtons,MechJeb2.Custom_Window_Editor,MechJeb2.Vessel_Info,MechJeb2.Surface_Info,MechJeb2.Scripting_Module,MechJeb2.Warp_Helper,MechJeb2.Smart_A_S_S_,MechJeb2.Maneuver_Planner
			visibleButtons = MechJeb2.Vessel_Info,MechJeb2.Surface_Info,MechJeb2.Custom_Window_Editor,MechJeb2.Smart_A_S_S_,MechJeb2.Maneuver_Planner,MechJeb2.Warp_Helper,MechJeb2.Scripting_Module
		}
		toolbar_772431615
		{
			x = 1974
			y = -3
			width = 250
			height = 38
			autoHide = False
			drawBorder = True
			useKSPSkin = True
			buttonOrder = __TOOLBAR_INTERNAL.configureVisibleButtons,Targetron.tgbutton,SurfaceExperimentPackage.SEPController,ContractsWindow.ContractWindowPlus,Kerbal_Construction_Time.MainButton
			visibleButtons = Kerbal_Construction_Time.MainButton,ContractsWindow.ContractWindowPlus,sirkut.IRButton
		}
	}_

**Comment by linuxgurugamer** [comment]
You have the wrong mod,  those messages are from the toolbarcontroller.  Those are harmless, and only happens when the game loads.  A low priority issue for now

Regarding the mainmenu stuff, I would have to dig to see what it is doing and why its there.  It doesnt hurt anything, so given how many other issues there are with some other mods, this is a low priority issue.

**Comment by linuxgurugamer** [comment]
Main menu section is needed
