### ISSUE TITLE
Closing the Button Visibility window leaves input locks applied

### ISSUE THREAD

**Issue by lpgagnon** [linuxgurugamer/ksp_toolbar#24]
Hovering anywhere in the Toolbar Button Visibility window turns on a whole bunch of input locks; hovering away correctly turns them back off. But Clicking the window's Close button closes the window without restoring the locks.

(locks get cleared if the window is reopened, hovered in and out; but since there's no way to close the window other than the Close button, that doesn't really help anything)

ksp 1.7.3, toolbar 1.7.22.2, ClickThroughBlocker 0.1.7.2

![Screen Shot 2019-11-12 at 11 09 29 PM](https://user-images.githubusercontent.com/5061230/68732594-00886100-05a2-11ea-8e62-c6c0527e0994.png)

**Comment by linuxgurugamer** [comment]
Should be resolved with latest version of the ClickThroughBlocker
