### ISSUE TITLE
Cannot move the icon or anything

### ISSUE THREAD

**Issue by ghost** [linuxgurugamer/ksp_toolbar#29]
I can click the arrow and "unlock" and click them but all of the options seem to do nothing.
The about me included.
once I click one of the options everything just *closes* idk whats up, I have the latest version and I have tried reinstalling the mod to no avail.

**Comment by ghost** [comment]
Also.
This happens when I open the menu; 
![image](https://user-images.githubusercontent.com/58830439/160212692-3c641041-9513-4393-ae22-47ccf9ae149b.png)
(that black box in the top left opens)

**Comment by ghost** [comment]
also should CTB (click through blocker) show up in the menu bar next to others like eve?

**Comment by linuxgurugamer** [comment]
This is not the appropriate place to ask for tech support.
Most likely you either have something badly installed or are missing one or more dependencies.
Please post on the KSP forum here, and include a link to the Player.log

[https://forum.kerbalspaceprogram.com/index.php?/topic/161857-15-toolbar-continued-common-api-for-draggableresizable-buttons-toolbar/](url)

This way other people besides myself can provide help
